In [1]:
# NUMPY 

# we use numpy cuz it is a memory efficient container with faster numerical operations.

# to make an numpy ARRAY.
import numpy as np
a=np.array([0,1,2,3])# we use "np.array([list])" if there is a list already to make an numpy array.
print(a)

print(np.arange(10))# "np.arrange(number)" is used when we need an numpy array in a range of desired number.
                    # here by using "np.arrange(10)" we made a numpy array of number in range of 10 i.e, 1-9.  
                    # arange can be consideres as "arrey in range"

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
# why is numpy useful
l=range(1000)
%timeit [i**2 for i in l]

843 µs ± 18.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
a=np.arange(1000)
%timeit a**2   

# if we compare the time(in micro second) in printed region of the two programs(1st one above this program) this program ran in 3.37 micro second where as the above one took 843 micro seconds which is significantly high.
# thats why  umpy is efficient.

3.37 µs ± 76.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
# CREAING AN ARRAY.

# 1-D array---- vector
a=np.array([1,2,3,4])
a # if i just type "a" it prints "array[list]" whereas when we type "print(a)" just an array(numpy array list) is printed.

array([1, 2, 3, 4])

In [8]:
print(a.ndim) # prints the dimensions of the array.
print(a.shape) #prints rows columns depended upon the dimensions of the array
                 #SHAPE PRINTS THE SHAPE OF THE MATRIX IN A FORM OF TUPLE.
# or
#np.shape(a) can be used
# here as there are 4 elements in the array the shape of it is (4,) i.e, (rows,columns(=0),3rd dimention row).

1
(4,)


In [17]:
# 2-D array---matrix

b=np.array([[8,3,9,4,6],[3,4,0,9,5]]) # 2-D array is nothing but list of lists in a numpy array.
print(b.ndim) 
print(b.shape)# (rows,columns)
print(len(b)) # rints the lenght of 1st dimension (which is rows)

2
(2, 5)
2


In [20]:
# 3-D array----tensor(anything beyond 2-D)
c=np.array([[[6,5,7],[9,1,4]],[[4,0,2],[7,3,2]]])
print(c.ndim)
print(c.shape)# (row,column,3d row)
print(len(c))

3
(2, 2, 3)
2


In [22]:
# functions for creating an array

#using arange function
# arange function is an array valued version of the python range function.
a=np.arange(10)# makes an arrey of range 10.
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
a=np.arange(1,10,2)# (start point,end point(not included),step size)
print(a)

[1 3 5 7 9]


In [25]:
# usng "linespace"
b=np.linspace(0,1,6)# (start point,end point(not included),number of points between them) 
                     # the last point in 3 points in 'linspace' is "number of points between start and end point" insread of "stepsize" which is in 'arange' and normal 'range'.
print(b)    

[0.  0.2 0.4 0.6 0.8 1. ]


In [51]:
# common arrays
a=np.ones((3,3))#*************************************************** touple inside list*******
print(a)
# in printed region we find "1." instead of just "1".  "1." means its a float

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
a=np.zeros([3,3])# prints zeros in a matrix of the given 'shape'.
print(a)
# doesn't work with "twos","threes" etc.

# for zeros,ones and eye the default datatype is "float". why float?******

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
b=np.eye(3)
# "np.eye()" gives us an identity matrix(every element except for the ones in the diagonal is "0") of the given shape. 
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
np.eye(3,2) #(3,2) identity matrix.

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [42]:
# creating arrays using "diag" function
a=np.diag([1,2,3,4])# gives us an 2-D array(matrix) with the provided list of elements as its diagonal.
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [43]:
print(np.diag(a))# to extract hte diagonal of the diagonal matrix.

[1 2 3 4]


In [44]:
# creating array using random elements.
a=np.random.rand(4)# gives an array of the given 'shape' with random elements.
print(a)

[0.90452446 0.98064735 0.6255695  0.72230256]


In [52]:
a=np.random.randn(4)#gives us an array of given shape with 'standard normal elements******'. 
a

array([ 0.21874919,  0.02317322,  0.4640172 , -0.31348588])

In [65]:
# datatype and datatype operations ********
a=np.array([1,2,3])
a.dtype # gives us the datatype o the array.

dtype('int32')

In [58]:
# we can expicitly specify the datatype of the array.
a=np.array([1,2,3,4],dtype='float64')
print(a.dtype)
print(a)
# in the printed array dot(".") after every number represents that it is a float.

float64
[1. 2. 3. 4.]


In [62]:
# other datatyps
d=np.array([1+2j, 3+9j])
d.dtype

dtype('complex128')

In [63]:
n=np.array(['hero','heroine'])
n.dtype

dtype('<U7')

In [67]:
# other datatypes are in screenshots(numpy(24))


In [68]:
# INDEXING AND SLICING

a=np.array([1,2,3,8,4,2,0,7,3,8])
print(a[5])

2


In [75]:
# indecies of 2-d arrays
a=np.diag([1,2,3,4])
print(a)
print(a[2,3])
print(a[1,1])
print(a[0])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
0
2
[1 0 0 0]


In [76]:
#assigning a value
a[1,1]=5
print(a)

[[1 0 0 0]
 [0 5 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [79]:
#slicing
a=np.arange(10)
print(a)
print(a[1:9:2])
print(a[1:5])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]
[1 2 3 4]


In [81]:
# assigning values by slicing
a[6:]=10 # "6:" represents 6:10 i.e, 6:the end of the list.
print(a)# every value from "6" is changed.

[ 0  1  2  3  4  5 10 10 10 10]


In [85]:
b=np.arange(5)
a[5:]=b[::-1] # this appends "a" from the provided(5(index) in this case) elements with the elements of "b" in reverse order(as -1 is mentioned).
print(a)

[0 1 2 3 4 4 3 2 1 0]


In [29]:
# slicing n dimentional array

r=np.diag([4,5,6,7])
r

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

In [30]:
r[0:2,0:2]

array([[4, 0],
       [0, 5]])

In [87]:
#COPIES AND VIEWS
a=np.arange(10)
b=a[::2]# by using this with numpy arrays instead of giving "b" a saperate memory it considers "b" as a part of "a" so doesn't give saperate memory for it in order to save memory.
b

array([0, 2, 4, 6, 8])

In [89]:
# to chack if 2 variables share memory.
np.shares_memory(a,b)# prints true if yes   else prints false.

True

In [91]:
b[0]=10 # as "a" and "b" shared memory if i change any element in either of them it changes for both if them.
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [92]:
# forcibally giving saperate memory
a=np.arange(10)
b=a[::2].copy()# now by adding ".copy()" we are forcibally giving "b" a saperate memory.
print(b)

[0 2 4 6 8]


In [93]:
np.shares_memory(a,b)

False

In [95]:
b[0]=9 # now it doesn't change element in "a" cuz we gave saperate memory to "b".
print(b)
print(a)

[9 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
#FANCY INDEXING
v=np.random.randint(0,20,15)# "np.random.randit(0,20,15)" creates an array of random elements from 0-20 (includes 20).
print(v)                    # it also repetes numbers.

[ 3  7  6  9 14  8 13 18 17  2 13  3 13 13  9]


In [16]:
mask=(v%2==0)# mask is like a condition which is applied when given a variable with the condition given
             # this condition filters out all the odd numbers and groups the remaining even numbers.
b=v[mask]# this syntax applies mask to the variable "v".
b

array([ 6, 14,  8, 18,  2])

In [19]:
v[mask]=-2 # this replaces every element of "v[mask]" with the desired/provided element ("-2" in this case).
print(v)

[ 3  7 -2  9 -2 -2 13 -2 17 -2 13  3 13 13  9]


In [23]:
# indexing with an array of integers
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
print(a[[2,6,3,9,7]])#prints multiple elements of a numpy array as a numpy array by taking their indexes.

[20 60 30 90 70]


In [25]:
# assignment of new values to multiple indices.
a[[3,5]]=123
a

array([  0,  10,  20, 123,  40, 123,  60,  70,  80,  90])

In [1]:
# ******NUMPY OPERATIONS*******

In [3]:
# elementwise operations
#basic operations

#with scalars
import numpy as np
a=np.array([1,2,3,4])
print(a+1)
print(a**2)

[2 3 4 5]
[ 1  4  9 16]


In [7]:
# all arthematic operations elementwise
b=np.ones(4)+1# now b=[2,2,2,2]
print(a-b) #substracting b from a=[1,2,3,4].

# **********************note: this doesnt work if shape of both "a" and "b" isn't same. here shape is "4".*********************

[-1.  0.  1.  2.]


In [5]:
a*b

array([2., 4., 6., 8.])

In [10]:
# matrix multiplication
c=np.diag([1,2,3,4])
print(c*c) # miltiplies two matrices.
print("**************")
#other syntax
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
**************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [15]:
# elementwise comparision
a=np.array([1,2,3,4])
b=np.array([3,2,9,4])
print(a==b)# compares each and every element of the given arrays and tells if they are equal or not in the form of "bool"
print(a>b) #i.e, gives "true" if the elements of same index in the two arrays are same else gives "false".

[False  True False  True]
[False False False False]


In [35]:
# arraywise comparision
a=np.array([1,2,3,4])
b=np.array([3,2,9,4])
c=np.array([1,2,3,4])

d=np.array_equal(a,b)
print(d)
f=np.array_equal(c,a)
print(f)
# gives "true" if all elements of the two arrays are equal else gives false.

False
True


In [22]:
#logical operations

a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)
print(np.logical_or(a,b))# this compares with "or" operator.
print(np.logical_and(a,b))# this compares with "and" operator.

[ True  True  True False]
[ True False False False]


In [23]:
#transcendental functions.
a=np.array([1,2,3,4])
np.sin(a)# prints "sin" of every element as an array


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [30]:
np.log(a)# for the log of elements in "a".

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [31]:
np.exp(a)# for e^x of the elemets of "a".

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [36]:
a=np.array([1,2,3,4])
print(a.sum())# sums up all the elements in "a".
#OR
print(np.sum(a))

10
10


In [37]:
b=np.array([[1,1],[2,2]])
print
b.sum(axis=0)#if axis is "0" the operation("sum" in this case) applies to columns if axix is "1" ti applies to rows.
             # here as it is columns it added elements in cllumns of the matrix(1+2=3)

array([3, 3])

In [38]:
b.sum(axis=1)

array([2, 4])

In [39]:
# other way
np.sum(b,axis=1)

array([2, 4])

In [44]:
x=np.array([1,4,3,6])
print(np.min(x))#   or   x.max()
print(np.max(x))#   or   x.min()
print(x.argmax())# prints the index of the largest element
print(x.argmin())# prints the index of the smallest element

#np.argmax(x) or np.argmin(x) could also be used

1
6
3
0


In [48]:
# logical operations (2)
print(np.all([True,True,False]))# "all" represents "and".
print(np.any([True,False,False]))# "any" represents "or".

False
True


In [3]:
a=np.zeros((50,50))


np.any(a!=0)# prints "true" if any of the element is not equal to zero.

False

In [51]:
np.all(a==0)

True

In [15]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
print(np.all((a<=b)&(b<=c))) #using two operations at a time in "np.all()".
#OR
print(((a<=b)&(b<=c)).all())

True
True


In [13]:
# statastics
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
np.mean(x)# gives mean value

1.75

In [16]:
np.median(y,axis=-1)# for median in axis=1/-1

array([2., 5.])

In [17]:
np.median(y,axis=0)

array([3., 4., 2.])

In [18]:
x.std()

0.82915619758885

In [24]:
 y.mean(axis=0) # median doesnt work in ths way.

array([3., 4., 2.])

In [25]:
data=np.loadtxt('populations.txt')

In [26]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [31]:
years,hares,lynxex,carrots=data.T
print(years)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [32]:
populations=data[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [33]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [35]:
populations.argmax(axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [36]:
#  BROADCASTING
#basic operations of numpy arrays are elementwise.
# broadcasting works on arrays of same size.nevertheless, it transforms the arrays to same size if they are not.

# refer screenshots (26-npy operations).

In [46]:
a=np.tile(np.arange(0,40,10),(3,1))#"tile(array,size)" converts the give array to the provided size.
print(a) 
print("**************************")
a=a.T # "a.T" is the transpose of "a".
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
**************************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [43]:
y=np.array([[1,2,3],[5,6,1]])
n=np.tile(y,(3,1))
print(n)

[[1 2 3]
 [5 6 1]
 [1 2 3]
 [5 6 1]
 [1 2 3]
 [5 6 1]]


In [48]:
b=np.array([1,2,3])
a+b   # this operation adds "b" to every row in "a" as "b" is a row. this operation tiles "b" 3 times rows to match its shape to that of "a".
      # this operation will be fruitful only if one or both arrays when tiled reshape to the similar shape.
      # tiling can be done only in 1 directon and only once for an array like if its a single row matrix it is tiled to 3 rows to match the other tile of 3 rows and same number of columns.
      # -if "b" has 3 columns and 1 row and "a"  has 4 and 3 it doesnt tile and gives us "shape mismatch" error.

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [50]:
a=np.arange(0,40,10)
np.shape(a)

(4,)

In [51]:
a=a[:,np.newaxis]
a.shape

(4, 1)

In [52]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [53]:
b

array([1, 2, 3])

In [54]:
a+b # tiles "a" by 3 columns and "b" by 3 rows.

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [59]:
# ARRAY SHAPE MANIPULATION

#flattening
a=np.array([[1,2,3],[4,5,6]])
a.ravel()      # this flattens the n-d array to a 1-d array.

array([1, 2, 3, 4, 5, 6])

In [60]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
a.T.ravel() # flattening the transpose of "a".

array([1, 4, 2, 5, 3, 6])

In [62]:
# reshaping
# this is opposite of "ravel".

a=np.array([[1,2,3],[4,5,6]])
b=a.ravel()# "b" is the flattened "view" of "a" not a "copy" of "a".hence it doesn't take saperate memory.
print(b) 

[1 2 3 4 5 6]


In [65]:
b=b.reshape(2,3)# reshapes the array to the provided shape.
b

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
b[0,0]=100 # this changes that particular element in "a" too.
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [71]:
#note and beware: rsahape can also return a copy.
a=np.zeros((3,2))
b=a.T.reshape(3*2)# (3,2) can also be used instead of (3*2)
b[0]=50
a # this returned "b" as a copy so "0th" element in "a" isn't changed.

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [74]:
#dimension shuffling.
a=np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [86]:
# resizing
a=np.arange(4)
np.resize(a,8) # OR a.resize((8,)) can also be used 

array([0, 1, 2, 3, 0, 1, 2, 3])

In [93]:
b=np.ones((3,2))
np.resize(b,(4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [97]:
c=np.array([[1,2,3],[4,5,6]])
np.resize(c,(5,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4]])

In [98]:
# sorting data
a=np.array([[3,1,8],[4,3,0]])# sorts in ascending order.
np.sort(a,axis=1)

array([[1, 3, 8],
       [0, 3, 4]])

In [100]:
j=np.argsort(a,axis=1)#gives indices of the sorted list.
j

array([[1, 0, 2],
       [2, 1, 0]], dtype=int64)

In [5]:
a[j]

NameError: name 'j' is not defined

In [2]:
import numpy as np
b=np.diag([1,2,3,4])
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [3]:
b[1]

array([0, 2, 0, 0])